login/urls.py
from . import views
from django.urls import path
app_name = 'login'
urlpatterns = [
    path('', views.Login.as_view(), name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include("polls.urls")),
    path('admin/', admin.site.urls),
    path('news/', include("news.urls")),
    path('login/', include("login.urls")),
]

news/urls.py
from . import views
from django.urls import path
app_name = 'news'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.ProcessData.as_view(), name='add_data'),
    path('save/', views.ProcessData.as_view(), name='save_data'),
    path('send_email', views.email_view, name='send_email'),
    path('send_email_complete', views.send_email_complete, name='send_email_complete'),

]

polls/urls.py
from . import views
from django.urls import path

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('getuser/', views.getUser,  name='get_user'),
    path('about/', views.about, name='about'),
    path('viewlist/', views.viewlist, name='view_list'),
    path('detail/<int:question_id>', views.detailView, name='detail'),
    path('<int:question_id>', views.vote, name="vote")
]

login/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.TextField(max_length=1000, blank=False, null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    time_pub = models.DateTimeField()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)

news/forms.py
from django import forms
from  .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', )


class SendEmail(forms.Form):
    title = forms.CharField(max_length=100)
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea)
    cc = forms.BooleanField()

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.contrib.auth import authenticate


class Login(View):

    def get(self, request):
        dt = "Login screen"
        return render(request, "login/login.html")

    def post(self, request):
        tendangnhap = request.POST.get('username')
        matkhau = request.POST.get('password')
        user_login = authenticate(username = tendangnhap, password = matkhau)
        if user_login is None:
            return HttpResponse('User khong ton tai')
        return HttpResponse("Ban vua bam dang nhap %s %s" %(tendangnhap, matkhau))

news/views.py
# Class base view
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm, SendEmail
from django.views import View


# Create your views here.


class IndexView(View):
    def get(self, request):
        dt = "Notification in scr"
        return HttpResponse(dt)


# class SendData(View):
#     def get(self, request):
#         post_data = PostForm()
#         return render(request, 'news/add_news.html', {'f': post_data})


class ProcessData(View):
    def get(self, request):
        post_data = PostForm()
        return render(request, 'news/add_news.html', {'f': post_data})

    def post(self, request):
        g = PostForm(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse('Data saved. OK!')
        else:
            return HttpResponse('Data not validate')

    def put(self):
        pass


def email_view(request):
    b = SendEmail()
    return render(request, 'news/email.html', {'f': b})


def send_email_complete(request):
    if request.method == "POST":
        m = SendEmail(request.POST)
        if m.is_valid():
            #context2 = {'email': m}
            title = m.cleaned_data['title']
            content = m.cleaned_data['content']
            email = m.cleaned_data['email']
            cc = m.cleaned_data['cc']
            context = {'tt': title, 'ct': content, 'em': email, 'cc': cc}
            return render(request, 'news/email_complete.html', {'email': context})
        else:
            return HttpResponse("Email not valid, sending error. Please check your email")
    else:
        return HttpResponse("Not request post")


# Function base view
# from django.shortcuts import render
# from django.http import HttpResponse
# from .forms import PostForm, SendEmail
#
#
# # Create your views here.
#
#
# def index(request):
#     return HttpResponse("Form news")
#
#
# def add_post(request):
#     post_data = PostForm()
#     return render(request, 'news/add_news.html', {'f': post_data})
#
#
# def save_news(request):
#     if request.method == "POST":
#         g = PostForm(request.POST)
#         if g.is_valid():
#             g.save()
#             return HttpResponse('Data saved. OK!')
#         else:
#             return HttpResponse('Data not validate')
#     else:
#         return HttpResponse("Not request post")
#
#
# def email_view(request):
#     b = SendEmail()
#     return render(request, 'news/email.html', {'f': b})
#
#
# def send_email_complete(request):
#     if request.method == "POST":
#         m = SendEmail(request.POST)
#         if m.is_valid():
#             #context2 = {'email': m}
#             title = m.cleaned_data['title']
#             content = m.cleaned_data['content']
#             email = m.cleaned_data['email']
#             cc = m.cleaned_data['cc']
#             context = {'tt': title, 'ct': content, 'em': email, 'cc': cc}
#             return render(request, 'news/email_complete.html', {'email': context})
#         else:
#             return HttpResponse("Email not valid, sending error. Please check your email")
#     else:
#         return HttpResponse("Not request post")

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Question, Choice

# Create your views here.
def index(request):
    myname = "Bac cowell dev"
    mySkill = ["python", "django", 'ruby', "java", "golang"]
    context = {"name": myname, 'skill': mySkill}
    return render(request, "polls/index.html", context)

def about(request):
    myname = "Bac cowell dev"
    mySkill = ["python", "django", 'ruby', "java", "golang", "rails", "javascript"]
    context = {"name": myname, 'skill': mySkill}
    return render(request, "polls/about.html", context)

def viewlist(request):
    list_question = Question.objects.all()
    context = {"dsquest": list_question}
    return render(request, "polls/question_list.html", context)

def detailView(request, question_id):
    q = Question.objects.get(pk=question_id)
    return render(request, "polls/detail_question.html", {"qs":q})

def vote(request, question_id):
    q = Question.objects.get(pk=question_id)
    # c = Choice()
    try:
        data = request.POST["choice"]
        c = q.choice_set.get(pk=data)
    except:
        HttpResponse("Lỗi khôgn có choice")
    c.vote = c.vote + 1
    c.save()
    return render(request, "polls/result.html", {"q":q})

def getUser(request):
    return HttpResponse("<h1>Get all User vote</h1>")

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Screen</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    <p><input type="text" name="username"></p>
    <p><input type="password" name="password"></p>
    <p><input type="submit" value="Login"></p>
</form>
</body>
</html>

news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'news:save_data' %}" method="post">
         {% csrf_token %}
        <p>{{ f.title }}</p>
        <p>{{ f.content }}</p>

        <input type="submit", value="Add Content">
    </form>
</body>
</html>

news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email</title>
</head>
<body>
<form action="{% url 'news:send_email_complete' %}" method="post">
             {% csrf_token %}
    <p>{{ f }}</p>
  <input type="submit" value="Send Email">
</form>

</body>
</html>

news/templates/news/email_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Email comlete</title>
</head>
<body>
    <h2>Email Sending Complete</h2>
    <h3>This is information your emails sending</h3>
    <table>
        <tr>
            <td>Title</td>
            <td>Content</td>
            <td>Email</td>
            <td>CC</td>
        </tr>
        <tr>
            <td>{{ email.tt }}</td>
            <td>{{ email.ct }}</td>
            <td>{{ email.em }}</td>
            <td>{{ email.cc }}</td>
        </tr>

    </table>
</body>
</html>

polls/templates/polls/about.html
{% extends 'polls/base.html' %}

{% block content123 %}
    <h1>This is templates</h1>
    <p>Hello world. Myname is <b>{{name}}</b></p>
    <p><b>My Skill programing language:</b></p>
   <ul>
    {% for item in skill %}
            <li>{{ item }}</li>
    {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static './polls/style.css' %}">
</head>
<body>
  <div class="header">
      <h1>Django Demo Website</h1>
  </div>
  <div class="menu">
      <ul>
          <li>Home</li>
          <li>About</li>
          <li>Product</li>
          <li>Contact</li>
      </ul>
  </div>
<div class="content">
    {% block content123 %}
    {% endblock %}
</div>
</body>
</html>

polls/templates/polls/detail_question.html
{% extends 'polls/base.html' %}

{% block content123 %}
    {% if qs %}
        <h2>{{  qs.question_text }}</h2>
        <form action="{% url 'polls:vote' qs.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for item in qs.choice_set.all %}
                    <li>
                        <input type="radio" value="{{ item.id }}" name="choice">{{ item.choice_text }}
                    </li>
                {% endfor %}
                <input type="submit" value="Submit">
            </ul>
        </form>
    {% endif %}
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content123 %}
    <h1>This is templates</h1>
    <p>Hello world. Myname is <b>{{name}}</b></p>
    <p><b>My Skill programing language:</b></p>
    <ul>
    {% for  item in skill %}
        {% if item != 'django' %}
            <li>{{ item }}</li>
        {% endif %}
    {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}

{% block content123 %}
    {% if dsquest %}
        {% for item in dsquest %}
        <a href="{% url 'polls:detail' item.id %} "><p >{{ item.question_text }}</p></a>
        {% endfor %}
    {% else %}
        <h3 style="color: red;">Khong co Du lieu Question nao</h3>
    {% endif %}
{% endblock %}

polls/templates/polls/result.html
{% extends 'polls/base.html' %}

{% block content123 %}
    {% if q %}
        {{ q.question_text }}
        <p>Kết quả cuộc bình chọn là: </p>
        {%  for item in q.choice_set.all  %}
            <p>{{ item.choice_text }} : <span style="color: red"> {{ item.vote }}</span></p>
        {% endfor %}
        <a href="{% url 'polls:view_list' %}"> Vote tiếp</a>
    {% endif %}
{% endblock %}